name: Build Docker image
on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to ghcr.io
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag image    
        run: |
          GITHUB_TOKEN=${{ secrets.PAT }}
          GITHUB_TOKEN_OWNER=${{ secrets.PAT_OWNER }}
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$COMMIT_SHA .
  
      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$COMMIT_SHA
